### PR TITLE
Added tables endpoint and pagination.

### PR DESCRIPTION
**Pull request by oyessb**

### CODE REVIEW

**Comment by likp** [comment]
Should we change so that the page object only holds the information of the the current page page size, current page  number and have the links to the next page self, previous page in the links. Similar too https://data.ssb.no/api/klass/v1/classifications.json

````mermaid
 classDiagram
      TableResult o-- Table : Tables
      TableResult o-- Page : Page
      TableResult o-- Link : Links
      Table o-- Link : Links
      TableResult: +Table[] Tables
      TableResult: +Page Page
      TableResult: +Link[] Links
      class Table {
          +string Id
          +string Label
          +string Description
          +date Updated
          +string[] Tags
          +Enum Category
          +Link[] Links
          +string[] VariableNames
          +string FirstPeriod
          +string LastPeriod
          +boolean Discontinued
      }
      class Page {
        +int size
        +int totalElements
        +int totalPages
        +int number
      }
      class Link {
         +string rel
         +string  href
      }
  
````

**Comment by JohannesFinsveen** [comment]
@likp Which drawing tool did you use ?

**Comment by likp** [comment]
Non, I just used mermaid syntax in the markup (https://mermaid-js.github.io/mermaid/#/classDiagram)

**Review by likp — APPROVED** [review]
Looks great now!

**Review by MikaelNordberg — APPROVED** [review]
Looks good

**Pull request merged**
